name: GraalVM Native Image Builds

on:
  push:
  # Remove none and add [ main ] to automatically trigger the action on push
    branches: none
  pull_request:
    branches: none
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # REGISTRY: ghcr.io
  # REGISTRY: container-registry.oracle.com
  # IMAGE_NAME: ${{ github.repository }}
  OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
  OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
  OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
  OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
  OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

jobs:
  build:
    name: Simple Spring Boot Sample on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          gds-token: ${{ secrets.GDS_TOKEN }}
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      
      - name: Build Native Image Using Maven
        run: mvn -Pnative native:compile

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          path: target/actions-demo

      # Define job to build and publish container image

      # Setup Container build action
      - name: Set up Container Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

  # Login to Oracle Container Registry

      - name: Get or create an OCIR Repository
        uses: oracle-actions/get-ocir-repository@v1.1
        id: get-ocir-repository
        with:
          name: actions-demo
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}

      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.1
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
      
      - name: Tag and push a container image
        id: tag-and-push-image
        run: |
          docker build -t actions-demo:native .
          docker tag "actions-demo:native" "${{ steps.get-ocir-repository.outputs.repo_path }}:native"
          docker push "${{ steps.get-ocir-repository.outputs.repo_path }}:native"

     # Login to GitHub Registry
      # - name: Login to Github Packages
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      
      # - name: Build image and push to GitHub Container Registry
      #   uses: docker/build-push-action@v3
      #   with:
      #     # Relative path to the place where source code with Dockerfile is located
      #     context: ./
      #     # Note: tags has to be all lower-case
      #     tags: |
      #       ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      #     # build on feature branches, push only on main branch
      #     push: ${{ github.ref == 'refs/heads/main' }}

      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}
